const formations={"4-3-3":[["GK",50,92],["LB",18,75],["CB",39,76],["CB",61,76],["RB",82,75],["CM",28,56],["CM",50,53],["CM",72,56],["LW",22,29],["ST",50,24],["RW",78,29]],"4-4-2":[["GK",50,92],["LB",18,75],["CB",39,76],["CB",61,76],["RB",82,75],["LM",20,53],["CM",40,55],["CM",60,55],["RM",80,53],["ST",40,27],["ST",60,27]],"3-5-2":[["GK",50,92],["CB",30,76],["CB",50,78],["CB",70,76],["LWB",14,55],["CM",35,56],["CM",50,52],["CM",65,56],["RWB",86,55],["ST",40,27],["ST",60,27]],"4-2-3-1":[["GK",50,92],["LB",18,75],["CB",39,76],["CB",61,76],["RB",82,75],["DM",40,60],["DM",60,60],["LW",22,42],["AM",50,39],["RW",78,42],["ST",50,23]],"3-4-3":[["GK",50,92],["CB",30,76],["CB",50,78],["CB",70,76],["LM",18,56],["CM",40,55],["CM",60,55],["RM",82,56],["LW",24,29],["ST",50,24],["RW",76,29]],"5-3-2":[["GK",50,92],["LWB",12,73],["CB",32,77],["CB",50,79],["CB",68,77],["RWB",88,73],["CM",30,54],["CM",50,51],["CM",70,54],["ST",40,27],["ST",60,27]]};

const STORE_KEY="footballLineupBuilderV4";
let currentFormation="4-3-3";
let players=Array.from({length:11},(_,i)=>({name:`Παίκτης ${i+1}`,number:String(i+1),custom:false,x:null,y:null,photo:""}));
let subs=["Αναπληρωματικός 1","Αναπληρωματικός 2"];
let drawMode=false, drawing=false, lines=[], currentLine=null;

const pitch=document.getElementById("pitch"),canvas=document.getElementById("drawCanvas"),ctx=canvas.getContext("2d"),pitchPlayers=document.getElementById("playersOnPitch"),playersForm=document.getElementById("playersForm"),formationSelect=document.getElementById("formation"),teamName=document.getElementById("teamName"),teamTitle=document.getElementById("teamTitle"),logoInput=document.getElementById("teamLogo"),logoPreview=document.getElementById("teamLogoPreview"),headerLogo=document.getElementById("headerLogo"),subsList=document.getElementById("subsList"),subsPreview=document.getElementById("subsPreview"),notes=document.getElementById("notes"),kitColor=document.getElementById("kitColor");

function save(){localStorage.setItem(STORE_KEY,JSON.stringify({currentFormation,players,subs,teamName:teamName.value,notes:notes.value,logo:headerLogo.src||"",kitColor:kitColor.value,lines}))}
function load(){try{const data=JSON.parse(localStorage.getItem(STORE_KEY)||"null");if(!data)return;currentFormation=data.currentFormation||currentFormation;players=(data.players&&data.players.length===11)?data.players:players;players=players.map((p,i)=>({...p,number:p.number??String(i+1)}));subs=data.subs||subs;teamName.value=data.teamName||"Η Ομάδα μου";notes.value=data.notes||"";kitColor.value=data.kitColor||"#0f172a";lines=data.lines||[];if(data.logo){logoPreview.src=data.logo;headerLogo.src=data.logo;headerLogo.style.display="block"}formationSelect.value=currentFormation}catch(e){}}
function setKit(){document.documentElement.style.setProperty("--kit",kitColor.value)}
function render(){setKit();renderPitch();renderPlayerInputs();renderSubs();teamTitle.textContent=teamName.value||"Η Ομάδα μου";resizeCanvas();drawAll();save()}
function getPlayerPosition(index){const d=formations[currentFormation][index];if(players[index]?.custom&&players[index].x!==null&&players[index].y!==null)return[d[0],players[index].x,players[index].y];return d}
function renderPitch(){pitchPlayers.innerHTML="";formations[currentFormation].forEach((item,index)=>{const[position,x,y]=getPlayerPosition(index);const p=players[index];const el=document.createElement("div");el.className="player";el.style.left=`${x}%`;el.style.top=`${y}%`;el.dataset.index=index;el.innerHTML=`<span class="player-number">${escapeHtml(p.number||"")}</span><span class="player-info"><small>${position}</small><span class="player-name">${escapeHtml(p.name||"")}</span></span>`;el.title="Κράτα πατημένο και σύρε. Διπλό κλικ για όνομα.";el.addEventListener("dblclick",()=>{const n=prompt(`Όνομα για θέση ${position}:`,p.name||"");if(n!==null){players[index].name=n.trim();render()}});enableDrag(el,index);pitchPlayers.appendChild(el)})}
function setPlayerFromClientPosition(index,clientX,clientY,element){const r=pitch.getBoundingClientRect();let x=((clientX-r.left)/r.width)*100,y=((clientY-r.top)/r.height)*100;x=Math.max(5,Math.min(95,x));y=Math.max(4,Math.min(96,y));players[index].x=+x.toFixed(2);players[index].y=+y.toFixed(2);players[index].custom=true;element.style.left=`${players[index].x}%`;element.style.top=`${players[index].y}%`;save()}
function enableDrag(element,index){let drag=false,startX=0,startY=0;element.addEventListener("pointerdown",e=>{if(drawMode)return;e.preventDefault();drag=true;startX=e.clientX;startY=e.clientY;element.setPointerCapture(e.pointerId);element.classList.add("dragging")});element.addEventListener("pointermove",e=>{if(!drag)return;e.preventDefault();if(Math.abs(e.clientX-startX)+Math.abs(e.clientY-startY)>1)setPlayerFromClientPosition(index,e.clientX,e.clientY,element)});element.addEventListener("pointerup",()=>{drag=false;element.classList.remove("dragging")});element.addEventListener("pointercancel",()=>{drag=false;element.classList.remove("dragging")})}
function renderPlayerInputs(){playersForm.innerHTML="";formations[currentFormation].forEach(([position],index)=>{const row=document.createElement("div");row.className="player-row";row.innerHTML=`<strong>${position}</strong><input type="text" value="${escapeHtml(players[index]?.name||"")}" data-kind="name"><input type="text" value="${escapeHtml(players[index]?.number||"")}" placeholder="Νο." data-kind="number"><button type="button">↺</button>`;row.querySelector('[data-kind="name"]').addEventListener("input",e=>{players[index].name=e.target.value;renderPitch();save()});row.querySelector('[data-kind="number"]').addEventListener("input",e=>{players[index].number=e.target.value;renderPitch();save()});row.querySelector("button").addEventListener("click",()=>{players[index].custom=false;players[index].x=null;players[index].y=null;render()});playersForm.appendChild(row)})}
function renderSubs(){subsList.innerHTML="";subsPreview.innerHTML="";subs.forEach((sub,index)=>{const row=document.createElement("div");row.className="sub-row";row.innerHTML=`<input type="text" value="${escapeHtml(sub)}"><input type="text" placeholder="Νο."><button type="button">×</button>`;row.querySelector("input").addEventListener("input",e=>{subs[index]=e.target.value;renderSubsPreview();save()});row.querySelector("button").addEventListener("click",()=>{subs.splice(index,1);renderSubs();save()});subsList.appendChild(row)});renderSubsPreview()}
function renderSubsPreview(){subsPreview.innerHTML="";subs.filter(Boolean).forEach(s=>{const pill=document.createElement("span");pill.className="sub-pill";pill.textContent=s;subsPreview.appendChild(pill)})}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}

function resizeCanvas(){const r=pitch.getBoundingClientRect();const ratio=window.devicePixelRatio||1;canvas.width=Math.round(r.width*ratio);canvas.height=Math.round(r.height*ratio);canvas.style.width=r.width+"px";canvas.style.height=r.height+"px";ctx.setTransform(ratio,0,0,ratio,0,0)}
function point(e){const r=pitch.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function drawArrow(a,b){ctx.strokeStyle="#ffffff";ctx.fillStyle="#ffffff";ctx.lineWidth=5;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();const ang=Math.atan2(b.y-a.y,b.x-a.x),len=18;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-len*Math.cos(ang-Math.PI/6),b.y-len*Math.sin(ang-Math.PI/6));ctx.lineTo(b.x-len*Math.cos(ang+Math.PI/6),b.y-len*Math.sin(ang+Math.PI/6));ctx.closePath();ctx.fill()}
function drawAll(){resizeCanvas();ctx.clearRect(0,0,canvas.width,canvas.height);lines.forEach(l=>drawArrow(l.a,l.b));if(currentLine)drawArrow(currentLine.a,currentLine.b)}
canvas.addEventListener("pointerdown",e=>{if(!drawMode)return;drawing=true;currentLine={a:point(e),b:point(e)};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener("pointermove",e=>{if(!drawMode||!drawing)return;currentLine.b=point(e);drawAll()});
canvas.addEventListener("pointerup",()=>{if(!drawMode||!drawing)return;drawing=false;if(currentLine){lines.push(currentLine);currentLine=null;drawAll();save()}});
window.addEventListener("resize",()=>{resizeCanvas();drawAll()});

formationSelect.addEventListener("change",e=>{currentFormation=e.target.value;players=players.map(p=>({...p,custom:false,x:null,y:null}));render()});
teamName.addEventListener("input",render);
notes.addEventListener("input",save);
kitColor.addEventListener("input",render);
logoInput.addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{logoPreview.src=reader.result;headerLogo.src=reader.result;headerLogo.style.display="block";save()};reader.readAsDataURL(file)});
document.getElementById("addSub").addEventListener("click",()=>{subs.push(`Αναπληρωματικός ${subs.length+1}`);renderSubs();save()});
document.getElementById("toggleDraw").addEventListener("click",e=>{drawMode=!drawMode;pitch.classList.toggle("drawing",drawMode);e.target.textContent=drawMode?"Σχεδίαση: Ανοιχτή":"Σχεδίαση: Κλειστή"});
document.getElementById("clearDraw").addEventListener("click",()=>{lines=[];drawAll();save()});
document.getElementById("reset").addEventListener("click",()=>{if(!confirm("Θέλεις σίγουρα να καθαρίσουν όλα;"))return;localStorage.removeItem(STORE_KEY);currentFormation="4-3-3";formationSelect.value=currentFormation;players=Array.from({length:11},(_,i)=>({name:`Παίκτης ${i+1}`,number:String(i+1),custom:false,x:null,y:null,photo:""}));subs=[];teamName.value="Η Ομάδα μου";notes.value="";kitColor.value="#0f172a";lines=[];logoInput.value="";logoPreview.removeAttribute("src");headerLogo.removeAttribute("src");headerLogo.style.display="none";render()});
async function makeCanvas(){drawAll();return await html2canvas(document.getElementById("captureArea"),{backgroundColor:"#e2e8f0",scale:2})}
document.getElementById("exportImage").addEventListener("click",async()=>{const c=await makeCanvas();const a=document.createElement("a");a.download="football-lineup.png";a.href=c.toDataURL("image/png");a.click()});
document.getElementById("exportPdf").addEventListener("click",async()=>{const c=await makeCanvas();const img=c.toDataURL("image/png");const{jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});const w=297,h=210;pdf.addImage(img,"PNG",0,0,w,h);pdf.save("football-lineup.pdf")});

load();render();
